export const errorTranslations: { [key: string]: string } = {
  CODE_ALREADY_SENT: 'کد تایید قبلا ارسال شده است',
  INVALID_CREDENTIALS: 'نام کاربری یا رمز عبور نامعتبر است',
  TOKEN_EXPIRED: 'نشست شما منقضی شده است، لطفا دوباره وارد شوید',
  INVALID_TOKEN: 'نشست نامعتبر است، لطفا دوباره وارد شوید',
  INVALID_PHONE_NUMBER: 'شماره موبایل نامعتبر است',
  USER_NOT_FOUND: 'کاربر یافت نشد',
  USER_BANNED: 'کاربر مسدود شده است',
  INVALID_FIRSTNAME: 'نام نامعتبر است',
  INVALID_LASTNAME: 'نام خانوادگی نامعتبر است',
  INVALID_EMAIL: 'ایمیل نامعتبر است',
  EMAIL_PROVIDER_NOT_SUPPORTED: 'ارائه دهنده ایمیل پشتیبانی نمی شود',
  GOAL_NOT_FOUND: 'هدف یافت نشد',
  INVALID_DEADLINE: 'مهلت نامعتبر است',
  INVALID_GENDER: 'جنسیت نامعتبر است',
  INVALID_BIRTH_DATE: 'تاریخ تولد نامعتبر است',
  DEADLINE_OVER: 'مهلت به پایان رسیده است',
  INVALID_GOAL_VALUE: 'ارزش هدف نامعتبر است',
  NOT_PAID: 'پرداخت نشده است',
  SAME_SUPERVISOR_AND_CREATOR: 'ناظر و ایجاد کننده نمی توانند یکسان باشند',
  ALREADY_SUPERVISED: 'قبلا نظارت شده است',
  EARLY_SUPERVISON: 'نظارت زود هنگام',
};
